# Python

## Files

---

In [1]:
%matplotlib inline

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [4]:
with open('art_data.dat') as f:
    read_data = f.read()
f.closed

True

In [9]:
read_data[2]

'3'

In [11]:
filename="art_data.dat"
data = np.loadtxt(filename)

In [14]:
data[0]
len(data)

10000

In [15]:
filename="art_data2.dat"
data = np.loadtxt(filename)

In [16]:
data

array([[ 1.7,  5.3, 10.2],
       [ 5.9, 11. ,  6.2],
       [-0.5,  4. ,  3.3],
       [ 8.8, -7.2, -1.2],
       [12.2, -1. ,  3.4]])

In [19]:
x=np.linspace(0,2*np.pi,10)
x

array([0.        , 0.6981317 , 1.3962634 , 2.0943951 , 2.7925268 ,
       3.4906585 , 4.1887902 , 4.88692191, 5.58505361, 6.28318531])

In [20]:
z=np.cos(x)
z

array([ 1.        ,  0.76604444,  0.17364818, -0.5       , -0.93969262,
       -0.93969262, -0.5       ,  0.17364818,  0.76604444,  1.        ])

In [21]:
np.savetxt('datatxt_1d.dat',x

In [22]:
np.savetxt('datatxt_2d.dat',(x,z))

In [41]:
xy=[]
for i in range(10):
    xy.append([i,np.cos(i)])
xy=np.array(xy)
xy

array([[ 0.        ,  1.        ],
       [ 1.        ,  0.54030231],
       [ 2.        , -0.41614684],
       [ 3.        , -0.9899925 ],
       [ 4.        , -0.65364362],
       [ 5.        ,  0.28366219],
       [ 6.        ,  0.96017029],
       [ 7.        ,  0.75390225],
       [ 8.        , -0.14550003],
       [ 9.        , -0.91113026]])

In [42]:
np.savetxt('datatxt_2dA.dat',xy)

In [52]:
x = np.linspace(-10, -1, 4)
y = np.linspace(1, 10, 6)
X, Y = np.meshgrid(x, y)

In [53]:
np.meshgrid(x, y)

[array([[-10.,  -7.,  -4.,  -1.],
        [-10.,  -7.,  -4.,  -1.],
        [-10.,  -7.,  -4.,  -1.],
        [-10.,  -7.,  -4.,  -1.],
        [-10.,  -7.,  -4.,  -1.],
        [-10.,  -7.,  -4.,  -1.]]), array([[ 1. ,  1. ,  1. ,  1. ],
        [ 2.8,  2.8,  2.8,  2.8],
        [ 4.6,  4.6,  4.6,  4.6],
        [ 6.4,  6.4,  6.4,  6.4],
        [ 8.2,  8.2,  8.2,  8.2],
        [10. , 10. , 10. , 10. ]])]

In [55]:
filename2="datatxt_2dA.dat"
data2 = np.loadtxt(filename2)
data2

array([[ 0.        ,  1.        ],
       [ 1.        ,  0.54030231],
       [ 2.        , -0.41614684],
       [ 3.        , -0.9899925 ],
       [ 4.        , -0.65364362],
       [ 5.        ,  0.28366219],
       [ 6.        ,  0.96017029],
       [ 7.        ,  0.75390225],
       [ 8.        , -0.14550003],
       [ 9.        , -0.91113026]])

In [56]:
import os        # OS module allows the interface with the underlying operating system
import math
import numpy as np
import matplotlib.pyplot as plt

os.getcwd()
os.chdir('..')

In [57]:
os.getcwd()

'E:\\EGGRAFA CONSTANTINOU_a15032006\\eggrafa_01\\CresstII\\Teaching\\astr288p_2018-fall\\astr288p_ckalapot\\astr288p_fall_2018'