# Python

## NumPy

---

NumPy is a fundamental Python library for scientific computing.

It allows as array oriented computing.

It provides support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays. (*wiki*)

## Fundamentals

In [1]:
import numpy as np
x=np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [47]:
import timeit

In [108]:
c="""\
import numpy as np
L=[]
for i in range(1000):
    L.append(i**2)
"""

In [109]:
timeit.timeit(stmt=c,number=1000)

0.48391616116850855

In [110]:
c1="""\
import numpy as np
y=np.arange(1000)
y**2
"""

In [111]:
timeit.timeit(stmt=c1,number=1000)

0.005894870948850439

In [114]:
x

array([1, 2, 3, 4])

In [115]:
x.ndim

1

In [116]:
x.shape

(4,)

In [117]:
len(x)

4

In [123]:
y=np.array([[1,2,3,4],[5,6,7,8]])
y

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [124]:
y.ndim

2

In [125]:
y.shape

(2, 4)

In [127]:
z=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]]])

In [129]:
print(z.ndim)
print(z.shape)
print(len(z))

3
(2, 3, 4)
2


In [130]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [132]:
np.arange(1,9,2)            # start, end (exclusive), step

array([1, 3, 5, 7])

In [134]:
np.linspace(0,10,20)            # start, end (inclusive), number of points

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [135]:
np.linspace(0,10,20,endpoint=False)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [136]:
np.ones(4)

array([1., 1., 1., 1.])

In [140]:
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [141]:
print(a.ndim)
print(a.shape)
print(len(a))

2
(3, 3)
3


In [142]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [143]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [145]:
np.diag(np.array([1,2,3]))

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [147]:
np.random.rand(7)            # assumes uniform distribution from 0 to 1

array([0.40232175, 0.89126621, 0.63158493, 0.50188267, 0.31624184,
       0.04499448, 0.51697575])

In [148]:
np.random.rand(7)

array([0.3133085 , 0.26074147, 0.04834448, 0.22162837, 0.21401519,
       0.67827214, 0.62524881])

In [153]:
np.random.seed(10)
np.random.rand(7)

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701,
       0.22479665, 0.19806286])

In [154]:
np.random.seed(10)
np.random.rand(7)

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701,
       0.22479665, 0.19806286])

In [157]:
np.random.rand(3,5)

array([[0.19894754, 0.8568503 , 0.35165264, 0.75464769, 0.29596171],
       [0.88393648, 0.32551164, 0.1650159 , 0.39252924, 0.09346037],
       [0.82110566, 0.15115202, 0.38411445, 0.94426071, 0.98762547]])

In [159]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [160]:
x.dtype

dtype('int32')

In [162]:
x=np.linspace(0,10,7)
x

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

In [163]:
x.dtype

dtype('float64')

In [165]:
y=np.array([1,2,3,4],dtype=float)
y.dtype

dtype('float64')

In [167]:
y=np.array([1,2,3,4],dtype='float32')
y.dtype

dtype('float32')

In [168]:
y

array([1., 2., 3., 4.], dtype=float32)

In [170]:
y=np.array([1,2,3,4],dtype='int64')
y.dtype

dtype('int64')

In [171]:
y=np.array([1,2,3,4],dtype=np.float32)
y.dtype

dtype('float32')

In [172]:
y

array([1., 2., 3., 4.], dtype=float32)

In [174]:
a=np.linspace(0,10,5)
a

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [175]:
a[0]

0.0

In [177]:
a[-1]

10.0

In [180]:
a[::-1]

array([10. ,  7.5,  5. ,  2.5,  0. ])

In [182]:
a=np.random.rand(4,4)
a

array([[0.63649114, 0.34634715, 0.04309736, 0.87991517],
       [0.76324059, 0.87809664, 0.41750914, 0.60557756],
       [0.51346663, 0.59783665, 0.26221566, 0.30087131],
       [0.02539978, 0.30306256, 0.24207588, 0.55757819]])

In [185]:
a[0,0]
a[2,3]

0.30087130894070724

In [187]:
a=np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [188]:
a[2:8:2]

array([2, 4, 6])

In [189]:
a[1:7]

array([1, 2, 3, 4, 5, 6])

In [190]:
a[:4]

array([0, 1, 2, 3])

In [191]:
a[:3]

array([0, 1, 2])

In [192]:
a[0]=-10

In [193]:
a

array([-10,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])

In [198]:
a[[1,5,10]]

array([ 1,  5, 10])

In [202]:
a=np.random.uniform(0,100,5)
a

array([18.84356599, 37.30623978, 74.4192136 , 18.62477742, 41.37978065])

In [203]:
a=np.random.uniform(0,100,(3,3))
a

array([[23.10053197, 65.36229291, 76.43747614],
       [83.48791308, 21.22128516, 96.19666008],
       [26.11403435, 86.37701958, 12.68744203]])

In [208]:
a[0][1]

65.36229290588096

In [210]:
a[0][0]=0
a

array([[ 0.        , 65.36229291, 76.43747614],
       [83.48791308, 21.22128516, 96.19666008],
       [26.11403435, 86.37701958, 12.68744203]])

In [217]:
a[(1,2)]

96.19666007543083

In [219]:
a[(1,2)]=4
a

array([[ 0.        , 65.36229291, 76.43747614],
       [83.48791308, 21.22128516,  4.        ],
       [26.11403435, 86.37701958, 12.68744203]])

In [223]:
a[2,2]=5
a

array([[ 0.        , 65.36229291, 76.43747614],
       [83.48791308, 21.22128516,  4.        ],
       [26.11403435, 86.37701958,  5.        ]])

In [226]:
a=np.random.randint(0,100,(5,5))
a

array([[51, 20,  5, 70, 61],
       [16, 74,  4, 22, 19],
       [85, 73, 35, 35, 11],
       [41, 54, 82, 19, 41],
       [81, 61, 10, 36,  0]])

In [232]:
b=a[2:,0:5:2]
b

array([[85, 35, 11],
       [41, 82, 41],
       [81, 10,  0]])

In [233]:
b=a[2:,[0,1,4]]
b

array([[85, 73, 11],
       [41, 54, 41],
       [81, 61,  0]])

- **Fancy index operations**

In [247]:
a=np.random.randint(0,100,20)
a

array([45, 94, 84, 20, 49, 33,  2, 97, 97, 98, 12, 82, 77, 66, 37, 31, 56,
       81, 87, 81])

In [248]:
b=(a % 2 == 1)
b

array([ True, False, False, False,  True,  True, False,  True,  True,
       False, False, False,  True, False,  True,  True, False,  True,
        True,  True])

In [249]:
am3=a[b]
am3

array([45, 49, 33, 97, 97, 77, 37, 31, 81, 87, 81])

In [250]:
am3=a[a%2==1]
am3

array([45, 49, 33, 97, 97, 77, 37, 31, 81, 87, 81])

In [251]:
a[a%2==1]=1
a

array([ 1, 94, 84, 20,  1,  1,  2,  1,  1, 98, 12, 82,  1, 66,  1,  1, 56,
        1,  1,  1])

## Numerical operations

In [253]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [254]:
x+10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [256]:
y=x**2
y

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [257]:
2**x

array([  1,   2,   4,   8,  16,  32,  64, 128, 256, 512], dtype=int32)

In [259]:
y=x**2+2**x
y

array([  1,   3,   8,  17,  32,  57, 100, 177, 320, 593], dtype=int32)

In [263]:
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [266]:
b=a*a  # not  matrix multiplication
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [268]:
b=np.dot(a,a)
b

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [22]:
a=np.random.randint(0,5,50)
a

array([4, 3, 2, 4, 4, 4, 2, 0, 1, 2, 0, 3, 2, 1, 0, 2, 1, 1, 2, 4, 0, 2,
       3, 2, 2, 0, 3, 4, 1, 1, 4, 1, 1, 1, 1, 3, 2, 1, 0, 4, 3, 3, 0, 0,
       4, 2, 2, 4, 3, 0])

In [23]:
b=np.random.randint(0,5,50)
b

array([0, 4, 0, 3, 4, 1, 3, 3, 1, 3, 0, 2, 3, 0, 4, 1, 1, 2, 2, 4, 2, 0,
       2, 0, 2, 4, 3, 3, 3, 4, 3, 2, 4, 2, 3, 2, 2, 1, 1, 0, 2, 0, 2, 1,
       4, 4, 4, 3, 1, 4])

In [281]:
c=(a==b)
c

array([False, False,  True, False,  True, False, False,  True, False,
        True, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False,  True,
       False, False, False, False,  True])

In [282]:
a[c]

array([2, 4, 3, 0, 1, 0, 2, 2, 4])

In [284]:
c=(a>b)
a[c]

array([2, 4, 3, 3, 1, 2, 4, 2, 2, 4, 4, 1, 4, 4, 3, 3, 3, 2, 1])

In [285]:
b[c]

array([0, 2, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0])

In [24]:
np.array_equal(a,b)

False

In [30]:
np.random.seed(10)
a=np.random.rand(10)
a

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701,
       0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981])

In [31]:
np.random.seed(10)
c=np.random.rand(10)
c

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701,
       0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981])

In [32]:
np.array_equal(a,c)

True

In [36]:
c=np.zeros(len(a))
for i in np.arange(len(a)):
    c[i]=a[i]+2e-10*(np.random.rand()-0.5)
c

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701,
       0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981])

In [41]:
np.array_equal(a,c)

False

In [42]:
np.allclose(a,c)      # default relative tolerance=1e-05, absolute tolerance=1e-08

True

In [43]:
np.allclose(a,c,1e-12,1e-12)

False

In [286]:
a=np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [290]:
k=0
for i in range(len(a)):
    for j in range(len(a[i])):
        k=k+1
        a[i][j]=k
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [292]:
b=a.T
b

array([[1., 4., 7.],
       [2., 5., 8.],
       [3., 6., 9.]])

In [293]:
np.transpose(a)

array([[1., 4., 7.],
       [2., 5., 8.],
       [3., 6., 9.]])

In [3]:
x=np.random.uniform(0,100,10)
x

array([58.40512843, 90.54095026, 47.21669552, 69.41890541, 61.04226642,
       94.17510359, 60.2062421 , 10.87922268,  2.61102401, 23.65195298])

In [5]:
np.sum(x)

518.1474913862123

In [7]:
x.sum()     # don't forget the ()

518.1474913862123

In [8]:
a=np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [9]:
k=0
for i in range(len(a)):
    for j in range(len(a[i])):
        k=k
        +1
        a[i][j]=k
a

array([[1., 2.],
       [3., 4.]])

In [10]:
a.sum()

10.0

In [11]:
a.sum(axis=0)     # columns

array([4., 6.])

In [12]:
a.sum(axis=1)     # rows

array([3., 7.])

In [2]:
x=np.random.uniform(0,100,10)
x

array([57.05738849, 21.15074477, 70.27230659, 51.26699518,  5.90308668,
       99.05119424, 87.10672027, 73.24770744, 25.79961059, 84.49479449])

In [18]:
x.min()

1.5972633821981774

In [19]:
x.max()

99.06972344340844

In [20]:
x.argmin()

5

In [21]:
x.argmax()

8

In [45]:
np.any(x>50)       # it is true if at least one element of x is greater then 50

True

In [46]:

np.all(x>50)

False

In [47]:
np.all(x>0)        # it is true if all the elements of x are greater then 0

True

In [3]:
y=x.reshape((2,5))
y

array([[57.05738849, 21.15074477, 70.27230659, 51.26699518,  5.90308668],
       [99.05119424, 87.10672027, 73.24770744, 25.79961059, 84.49479449]])

In [4]:
y=x.reshape((5,2))
y

array([[57.05738849, 21.15074477],
       [70.27230659, 51.26699518],
       [ 5.90308668, 99.05119424],
       [87.10672027, 73.24770744],
       [25.79961059, 84.49479449]])

In [5]:
y.flatten()          # see also ravel

array([57.05738849, 21.15074477, 70.27230659, 51.26699518,  5.90308668,
       99.05119424, 87.10672027, 73.24770744, 25.79961059, 84.49479449])

In [9]:
x=np.random.uniform(0,100,10)
x.resize((20,))
x

array([84.98609093, 23.57667038, 89.57209731, 87.59094087, 50.07106344,
       92.08721205,  1.37216468, 43.71885634, 89.99106303, 64.46486587,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ])

**Strange behavior**

In [12]:
x=np.random.uniform(0,100,10)
y=x
x.resize((20,))
x

ValueError: cannot resize an array that references or is referenced
by another array in this way.  Use the resize function

In [14]:
x.sort()
x

array([ 2.90902816,  4.12998852, 10.8344695 , 20.4874548 , 48.85421727,
       59.95503698, 65.04459702, 74.48202603, 89.26241256, 97.71004519])

In [49]:
x=np.random.uniform(0,100,10)
x

array([18.53678296, 46.13832472, 61.16569947, 70.56424846,  9.87797215,
       18.72763683, 47.6910426 , 36.61789298, 62.10406955,  1.61835878])

In [50]:
y=x.reshape((5,2))
y

array([[18.53678296, 46.13832472],
       [61.16569947, 70.56424846],
       [ 9.87797215, 18.72763683],
       [47.6910426 , 36.61789298],
       [62.10406955,  1.61835878]])

In [51]:
y.sort(axis=0)  # sorts each column separately
y

array([[ 9.87797215,  1.61835878],
       [18.53678296, 18.72763683],
       [47.6910426 , 36.61789298],
       [61.16569947, 46.13832472],
       [62.10406955, 70.56424846]])

In [53]:
x.argsort()

array([1, 0, 2, 3, 5, 7, 4, 6, 8, 9], dtype=int64)

In [56]:
x=np.random.uniform(0,100,10)
y=x.reshape((5,2))
y

array([[ 7.22718787, 10.57875778],
       [36.8650993 , 37.68238166],
       [12.1995209 , 35.6147167 ],
       [40.90848103, 70.10396453],
       [10.18746222, 73.64542609]])

In [57]:
y[y[:,0].argsort()]

array([[ 7.22718787, 10.57875778],
       [10.18746222, 73.64542609],
       [12.1995209 , 35.6147167 ],
       [36.8650993 , 37.68238166],
       [40.90848103, 70.10396453]])

- **Explore the numerical functions**

In [58]:
np.sin(x)

array([ 0.80991229, -0.91438241, -0.74063339, -0.0167294 , -0.35867654,
       -0.870982  , -0.06772465,  0.83543629, -0.69086461, -0.98348344])

In [59]:
np.log10(x)

array([0.85896934, 1.02443467, 1.56661541, 1.57613834, 1.08634278,
       1.55162949, 1.61181335, 1.84574258, 1.00806601, 1.86714578])

In [60]:
np.sqrt(x)

array([2.68834296, 3.25250024, 6.07166364, 6.1385977 , 3.49278126,
       5.96780669, 6.39597381, 8.37281103, 3.19178042, 8.58169133])

In [61]:
np.pi

3.141592653589793

In [64]:
np.exp(1)

2.718281828459045